// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package backend

import (
	"context"
)

const getWindowGeometry = `-- name: GetWindowGeometry :one
SELECT id, width, height, x, y
FROM window
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetWindowGeometry(ctx context.Context) (Window, error) {
	row := q.db.QueryRowContext(ctx, getWindowGeometry)
	var i Window
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.X,
		&i.Y,
	)
	return i, err
}

const insertDefaultWindow = `-- name: InsertDefaultWindow :exec
INSERT INTO window (
    id,
    width,
    height,
    x,
    y
)
VALUES (
    1,
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertDefaultWindowParams struct {
	Width  float64
	Height float64
	X      float64
	Y      float64
}

func (q *Queries) InsertDefaultWindow(ctx context.Context, arg InsertDefaultWindowParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultWindow,
		arg.Width,
		arg.Height,
		arg.X,
		arg.Y,
	)
	return err
}

const updateWindowGeometry = `-- name: UpdateWindowGeometry :exec
UPDATE window
SET
    width  = ?1,
    height = ?2,
    x      = ?3,
    y      = ?4
WHERE id = 1
`

type UpdateWindowGeometryParams struct {
	Width  float64
	Height float64
	X      float64
	Y      float64
}

func (q *Queries) UpdateWindowGeometry(ctx context.Context, arg UpdateWindowGeometryParams) error {
	_, err := q.db.ExecContext(ctx, updateWindowGeometry,
		arg.Width,
		arg.Height,
		arg.X,
		arg.Y,
	)
	return err
}
